#!/bin/bash
# ~~~~~~~~~~  SET VARIABLES  ~~~~~~~~~ #
volten="SMAKA HS!"

# ~~~~~~~~~~  CREATE FUNCTIONS  ~~~~~~~~~ #
cleanup()
#exempel
{
#killall hping3
}

# ~~~~~~~~~~  SETUP EXIT TRAP  ~~~~~~~~~ #
control_c()
# run if user hits control-c
{
echo -en "\n*** Ouch! Exiting ***\n"
cleanup
exit $?
}

# trap keyboard interrupt (control-c)
trap control_c SIGINT

# ~~~~~~~~~~  INITIALIZATION  ~~~~~~~~~ #

# ~~~~~~~~~~  Environment Setup ~~~~~~~~~~ #
    NORMAL=`echo "\033[m"`
    BLUE_TEXT=`echo "\033[36m"` #Blue
    NUMBER=`echo "\033[33m"` #yellow
    FGRED=`echo "\033[41m"`
    RED_TEXT=`echo "\033[31m"` #Red
    ENTER_LINE=`echo "\033[33m"`
    INTRO_TEXT=`echo "\033[32m"` #green and white text
    INFOS=`echo "\033[103;30m"` #yellow bg
    SUCCESS=`echo "\033[102;30m"` #green bg
    WARNING=`echo "\033[101;30m"` #red bg
    WARP=`echo "\033[106;30m"` #lightblue bg
    BLACK=`echo "\033[109;30m"` #SPACE bg
    END=`echo "\033[0m"`
# ~~~~~~~~~~  Environment Setup ~~~~~~~~~~ #

# ~~~~~~~~~~  ROOT CHECK! ~~~~~~~~~ #
FILE="/tmp/out.$$"
GREP="/bin/grep"
#Only root should run this.
if [[ $EUID -ne 0 ]]; then
	cowsay -f sodomized-sheep "Run as root." 1>&2
	exit 1
fi


# ~~~~~~~~~~  BEGINNING OF SCRIPT BELOW ~~~~~~~~~ #
cowsay -f head-in 'Björn! -Rayneth 2014'
cowsay -f vader $volten
